FROM oven/bun:1.2.16 

ENV NODE_ENV=production

WORKDIR /app


COPY bun.lock package.json /app/
COPY ./src/ /app/src/

RUN bun install --frozen-lockfile

ENV PORT=8080

EXPOSE $PORT 

ENTRYPOINT [ "bun", "run", "src/HeadlessServer.ts"]