FROM oven/bun:1.0.16 

ENV NODE_ENV=production

WORKDIR /app

COPY ./package*.json /app/
COPY ./src/ /app/src/

RUN bun install --frozen-lockfile

ENV PORT=8080

EXPOSE $PORT 

ENTRYPOINT [ "bun", "run", "src/HeadlessServer.ts"]